openapi: 3.0.1
info:
  title: Opene - Externa listor
  description: "Extern lista med anst채llda."
  contact:
    name: Andreas Nordman
    email: andreas.nordman@ostersund.se
  version: 1.0.24
servers:
  - url: /api/opene/rest/listor
    variables:
      scheme:
        default: https
        enum:
          - https
paths:
  /heroma/employees:
    get:
      tags:
        - Heroma
      summary: En lista med anst채llda under en viss chef.
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
            description: chefens anv채ndarnamn
      responses:
        '200':
          description: Lista med medarbetare under chefen returneras.
        default:
          description: Ett fel har intr채ffat
tags:
  - name: Heroma
    description: Listor med koppling mot Heromas databas.
